### ISSUE TITLE
Colab error: OSError: data/hi-transformer does not appear to have a file named config.json. Checkout 'https://huggingface.co/data/hi-transformer/main'

### ISSUE THREAD

**Issue by Tylersuard** [coastalcph/hierarchical-transformers#10]
Traceback (most recent call last):
  File "/content/hi-transformers/language_modelling/run_mlm.py", line 626, in <module>
    main()
  File "/content/hi-transformers/language_modelling/run_mlm.py", line 335, in main
    config = HATConfig.from_pretrained(model_args.config_name, **config_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 590, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: data/hi-transformer does not appear to have a file named config.json. Checkout 'https://huggingface.co/data/hi-transformer/main'

**Comment by Tylersuard** [comment]
I would love to try your code, but it is just not working.  Try the Colab notebook yourself: https://colab.research.google.com/drive/15feh49wqBshgkcvbO6QypvJoa3dG6P5S?usp=sharing

I just keep getting errors.

**Comment by iliaschalkidis** [comment]
Hi @Tylersuard,

There were some minor bugs due to the major renaming from `hi-tranformer` to `hat` before the release. Now, things should work fine.

Consider this Colab example: https://colab.research.google.com/drive/15feh49wqBshgkcvbO6QypvJoa3dG6P5S?usp=sharing

I couldn't install `torch_xla` for TPU support in the Colab environments with python 3.9, so I worked with a GPU env.

At the moment, training a model from scratch (config) is not possible, so consider warm-starting a model from a BERT or RoBERTa checkpoint. 

```
python models/hat/convert_roberta_to_htf.py --layout p1 --max_sentences 32
!python models/hat/convert_bert_to_htf.py --layout p1 --max_sentences 32
```

If it's important for you to start from scratch, consider initializing a BERT/RoBERTa from scratch, and then use it as a "fake" warm-start model.
